### ISSUE TITLE
dashboard: data download function - add functionality to download selected measure for all geographies and years

### ISSUE THREAD

**Issue by klinehan1** [uva-bi-sdad/social_data_commons#13]
Front-end download prompt should show a choice to download selected data or file that includes the selected measure (so that the selected measure has all geographies and years)

**Comment by wanghalan** [comment]
- Built out [sdc.measures](https://github.com/uva-bi-sdad/sdc.measures) which are files split on all valid csv's in the tracked public repos in [sdc.all_dev](https://github.com/uva-bi-sdad/sdc.all_dev)

**Comment by wanghalan** [comment]
Download button is live: https://uva-bi-sdad.github.io/community_example
