### ISSUE TITLE
dashboard: site rebuilds twice a week on a regular schedule (COB Tuesday and Friday)

### ISSUE THREAD

**Issue by klinehan1** [uva-bi-sdad/social_data_commons#15]

**Comment by wanghalan** [comment]
hacim test run with Neil complete

https://github.com/uva-bi-sdad/community_example/blob/c1e4c58a9fd44db5e928b4322d219c1690818409/.github/workflows/hacim.yml#L4

**Comment by wanghalan** [comment]
Just needs to add the runner on a per-repository basis, not in social_data_commons
